services:
  api:
    build: .
    ports:
      - "8080:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    restart: always
    # entrypoint: ["tail", "-f", "/dev/null"]
  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
